from .home import home
from .landing_page.list import ticket_list_s
from .onboardings.list import location_list_on
from .onboardings.form import location_form_on
from .first_rigs.form import rig_form_on
from .first_rigs.list import rig_list_on
from .auth.logout import logout_user
from .tickets.list import ticket_list
from .tickets.form import ticket_form
from .tickets.details import ticket_details
from .rigs.list import rig_list
from .rigs.form import rig_form
from .rigs.details import rig_details
from .locations.list import location_list
from .locations.form import location_form
from .miners.list import miner_list
from .auth.register import register