# Generated by Django 3.0.4 on 2020-03-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybapp', '0002_auto_20200319_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miner',
            name='location',
        ),
        migrations.AddField(
            model_name='miner',
            name='city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
