# Generated by Django 3.0.4 on 2020-03-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybapp', '0002_auto_20200313_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetype',
            old_name='issue_type_name',
            new_name='itn',
        ),
    ]
