# Generated by Django 3.0.4 on 2020-03-14 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybapp', '0003_auto_20200314_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetype',
            old_name='itn',
            new_name='issue',
        ),
    ]
