# Generated by Django 3.0.4 on 2020-03-14 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybapp', '0005_auto_20200314_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuetype',
            options={'verbose_name': 'cat', 'verbose_name_plural': 'cats'},
        ),
        migrations.RenameField(
            model_name='issuetype',
            old_name='itn',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='itn',
            new_name='category',
        ),
    ]
