# Generated by Django 3.0.4 on 2020-03-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybapp', '0006_auto_20200314_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='completed',
        ),
    ]
