# Generated by Django 3.0.4 on 2020-03-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybapp', '0008_auto_20200314_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='miner',
        ),
    ]
